sudo: false
language: python
python:
  - 2.6
  - 2.7
  - pypy
  - 3.3
  - 3.4
  - 3.5.1
install:
  - if [[ $TRAVIS_PYTHON_VERSION == '2.6' ]]; then pip install unittest2; fi
  - pip install --upgrade -r test-requirements.txt
script: nosetests --logging-level=DEBUG
after_success:
  - codecov
  - CODECLIMATE_REPO_TOKEN=ed39a2c039a29b0965bfdd243fea7caba2a83a4945bbd69fe95f506066754bd1 codeclimate-test-reporter
services:
  - rabbitmq
deploy:
  distributions: sdist bdist_wheel
  provider: pypi
  user: crad
  on:
    python: 2.7
    tags: true
    all_branches: true
  password:
    secure: "ls9ja4J6bcirOvWVCvPAWboaOK6O0Pr/aZmHiifUYKEBqUg8D9PB7JyeXybMthXSx+jkHrFp6pL/IjYGrMYQ3gomZ+fsQTavNLxZxEHyLxDf7LVBxQ0KMNNh+GyF7qi9U749MlZBf9JgBFbAgnwCZRnlzCM8j7PxcFevYv4gouE="
